### ISSUE TITLE
Incorrect plotting from external file. Repeating C axis labels

### ISSUE THREAD

**Issue by JKomp** [AymericFerreira/Plotly_barchart3D#12]
I ran into two issues. The first was a naming issue between your examples and the code. Your README examples import plotly_barcharts_3d but in the code it's plotly_bar_charts_3d. Also, the data file imported in examples 2 and 3 is dataExample.csv not dataBar.csv

The second issue is more troublesome. The code doesn't seem to be handling the C axis correctly. It's duplicating C. See the attached screenshot.
<img width="799" alt="Plotly_barchart3D_issue" src="https://user-images.githubusercontent.com/15156633/213878226-18bec38a-07f3-4e4e-b4ac-22a79a15b822.png">

**Comment by AymericFerreira** [comment]
Thank you for reporting these bugs.
I will change the doc' according to new functions names. 

For your graph problem you can temporarely use the function bar_charts3d_from_array :
`fig = bar_charts3d_from_array(df['Gamma'], df['C'], df['score 1'], x_title='Gamma', y_title='C', color='x+y')`
that will lead to
![image](https://user-images.githubusercontent.com/26620341/213932319-01416c66-b23e-49e3-b49c-56e3c7626621.png)

I will close the issue when I will solve this issue in the main branch
