### ISSUE TITLE
Make subplots with various barchart3D

### ISSUE THREAD

**Issue by ajtarraga** [AymericFerreira/Plotly_barchart3D#18]
Hi @AymericFerreira 

I am trying to use the project [https://github.com/AymericFerreira/Plotly_barchart3D](url) to make a comparative while performance is analized in different scenarios. However, I am not able to make a subplot of various barchart3D graphs. I have the following code:

> figs = make_subplots(rows=1, cols=2, specs=[ [{'type': 'scene'}, {'type': 'scene'}]])
> figs.add_trace(fig.data[0], row=1, col=1)
> figs.add_trace(fig2.data[0], row=1, col=2)

Where fig and fig2 are two instances of barchart3D. While I execute this code, I obtained the following output:
[3d_print.pdf](https://github.com/AymericFerreira/Plotly_barchart3D/files/10970396/3d_print.pdf)

Where fig and fig2 are:

[3d_printX.pdf](https://github.com/AymericFerreira/Plotly_barchart3D/files/10970401/3d_printX.pdf)
[3d_printY.pdf](https://github.com/AymericFerreira/Plotly_barchart3D/files/10970402/3d_printY.pdf)

How can I subplot many barchart3D instances?

Thank you in advance!

**Comment by AymericFerreira** [comment]
Hello, 
I'm sorry for the super late answer. Your problem here is that you take only one barchart from your fig and one from your fig2. You need to loop over your fig.data. Here is an example :

```
    from plotly.subplots import make_subplots
    xdf = pd.Series([1, 10])
    ydf = pd.Series([2, 4])
    zdf = pd.Series([10, 30, 20, 45])
    fig = plotly_bar_charts_3d(xdf, ydf, zdf, color='x+y')

    figs = make_subplots(rows=1, cols=2, specs=[[{'type': 'scene'}, {'type': 'scene'}]])
    for trace in fig.data:
        figs.add_trace(trace, row=1, col=1)
    for trace in fig.data:
        figs.add_trace(trace, row=1, col=2)
    figs.show()
```

And it should give you the excepted graph
![image](https://user-images.githubusercontent.com/26620341/228857270-0d3bf9ae-33c2-4c92-8aa1-085d50b0f922.png)
