### ISSUE TITLE
index out of range 

### ISSUE THREAD

**Issue by rajeshkalakoti** [AymericFerreira/Plotly_barchart3D#6]
could you please check with these values once 
features = [2,3,5,10,20]
neighbours = [31,24,10,28,48]
accuracies = [0.9727,0.9994,0.9994,0.9995,0.9995]

**Comment by AymericFerreira** [comment]
Your input is not the accepted behaviour. I wrote this code thinking about showing grids of parameters, which is not your case.
Although I think it would be a pretty nice addition

For the moment the workaround is :
```
features = [2, 2, 2, 2, 3, 3, 3, 3, 5, 5, 5, 5, 10, 10, 10, 10]
neighbours = [31, 24, 10, 48, 31, 24, 10, 48, 31, 24, 10, 48, 31, 24, 10, 48]
accuracies = [0.9727, None, None, None, None, 0.9994, None, None,
              None, None, 0.9995, None, None, None, None, 0.9995]
plotly_barcharts_3d(features, neighbours, accuracies,
                    x_title="Features", y_title="Neighbours", z_title="Accuracy").show()
```

It will result in :
![barchart_1](https://user-images.githubusercontent.com/26620341/116097085-ce749d00-a677-11eb-8543-ddede37d1649.png)

I will modify the code to make it easier to use your type of input.

**Comment by rajeshkalakoti** [comment]
Thank you so much. I appreciate you. your code is kind  of  tricky to understand for me.  could you please give me the code? I also want to test it. I tested on your code. but  its not not working for me.

**Comment by rajeshkalakoti** [comment]
Hey, it's fine, thank you. it's working perfectly. could you please modify the code soon  for my input ?

**Comment by AymericFerreira** [comment]
Code is updated, tell me if it suits you and if it's working for you

**Comment by rajeshkalakoti** [comment]
well, it's perfectly working for  length five elements. but it's index out of range error for more than five. But I understood  it. thank you so much.

**Comment by AymericFerreira** [comment]
Can you please provide your input ? 
I tested with : 

```
    features = [2, 3, 5, 10, 20, 30]
    neighbours = [31, 24, 10, 28, 48, 54]
    accuracies = [0.9727, 0.9994, 0.9994, 0.9995, 0.9995, 0.992]
```

And it's working.
If a feature or a neighbour is present two times it will not work actually but I'm thinking about a workaround.

**Comment by rajeshkalakoti** [comment]
i think it would be so better if x,y, z values are N number values. I have so many features, Neighbours, accuracies.

**Comment by AymericFerreira** [comment]
For the moment there is two possibilities : 

Or len(accuracies) = len(unique_features) * len(unique_neighbours) 
and in this case you have a grid of len(unique_features) * len(unique_neighbours) as in the documentation

Or len(accuracies) = len(unique_features) = len(unique_neighbours)
and in this case you have a result similar to what I posted earlier.

If you have non unique features and/or neighbours I will release a new fix soon,

**Comment by rajeshkalakoti** [comment]
Hey, 
could you please try your code like this? 

accuracies = [0.9727,0.9994,0.9994,0.9995,0.9995],  - accuracy is in one color
Precision = [ 0.9991 ,0.9991,0.9991, 0.9991, 0.9992]  - precision is in one color
Recall = [0.9545,1.0000,0.9998, 1.0000,1.0000]  - Recall is in one color 
F1 score = [0.9763,0.9995,0.9995, 0.9995, 0.9996] - f1 score is in one color 

neighbours = [31,24,10,28,48]
features = [2,3,5,10,20]

Thank you,

**Comment by rajeshkalakoti** [comment]
accuracies, precision, recall , f1-score are in one-Axis.  Neighbours are in one-axis, Features are in one-axis.

**Comment by rajeshkalakoti** [comment]
@AymericFerreira  are you trying your  code for my problem? can you please?

**Comment by rajeshkalakoti** [comment]
@AymericFerreira could you please tell me how to change the axis ticking label? means I don't want change the values of positions. but x-axis should be like in order from 1 to number n. thank you so much, very much appreciated if you  tell me.
