### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by wtbuono** [AymericFerreira/Plotly_barchart3D#7]
First of all, your code seems really good and helpful, it is everything I wanted. However, the examples provided does not compile with the current version of the code. The error message I get is 

"IndexError: list index out of range"

Also, I cannot produce a plot like the one in the first example. I always get a diagonal bar arrangement, instead of grid one, like in the examples.

Again, congratulations on this code.

**Comment by AymericFerreira** [comment]
Can you please tell me which code you are running ? I tried it and I don't have any error with : 


features = [2, 3, 5, 10, 20]
neighbors = [31, 24, 10, 28, 48]
accuracies = [0.9727, 0.9994, 0.9994, 0.9995, 0.9995]
plotly_barcharts_3d(features, neighbors, accuracies,
                    x_title="Features", y_title="Neighbors", z_title="Accuracy").show()

**Comment by AymericFerreira** [comment]
Ok, I did quite a messy update to deal with this error. 
Now it should work

Note that I will refactor later when I will have more time

**Comment by AymericFerreira** [comment]
I previously solved the problem. I finally did a lot of refactoring, so I will close this issue
